apiVersion: v1
kind: Service
metadata:
  name: backend-balancer
spec:
  selector:
    app: efurni-backend-pod
  ports:
    - port: 5000 #front-end port
      targetPort: 80 #back-end port
  type: LoadBalancer