apiVersion: v1
kind: Service
metadata:
  name: frontend-balancer
spec:
  selector:
    app: efurni-frontend-pod
  ports:
    - port: 8080 #front-end port
      targetPort: 80 #back-end port
  type: LoadBalancer