apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: efurni-backend-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: efurni-backend-pod
    spec:
      containers:
        - name: efurni-core-container
          image: efurni.azurecr.io/efurni-core:latest
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
