apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:4.0
          resources:
            limits:
              memory: "200Mi"
              cpu: "250m"
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis-config